CHG Add/Assign Questions Button Color Issue #320
AnubisLMS/Anubis pull request #378
Opened 2022-04-06 02:05 UTC by AaronBinChen

2022-04-26 01:38 UTC, synoet commented on web/src/components/core/Assignment/QuestionControls.jsx
> +                  // style = {{
Please remove your comments

2022-05-03 01:44 UTC, AaronBinChen commented on web/src/components/core/Assignment/QuestionControls.jsx
> +                  // style = {{
removed

2022-05-03 01:51 UTC, synoet approved these changes
LGTM!

2022-05-03 01:52 UTC, synoet requested changes
Sorry that approval was a little preemptive. Please sign and squash your commits.

2022-09-10 00:28 UTC, closed without merging