FIX disable warning msg on iPadOS browser
AnubisLMS/Anubis pull request #382
Opened 2022-04-26 00:56 UTC by AcKindle3

Solves #285.

The device warning shown for the iPadOS browser is disabled, by detecting the device with the flag `isTablet` using package `react-device-detect`.

Notice a change from `isBrowser` to `isDesktop`, in which the latter is preferred over `isBrowser` ([source](https://github.com/duskload/react-device-detect/blob/ec3cdbfd410f1e8dd7272fb2f131eb8bdec43ec2/docs/selectors.md))

2022-04-26 00:57 UTC, AcKindle3 commented
Testing is WIP.

2022-04-26 01:32 UTC, synoet commented
This looks good, thank you for taking on this issue.

Please sign your commits, then I'll merge it.

2022-04-26 01:40 UTC, synoet requested changes
This looks good, thank you for taking on this issue.

Please sign your commits, then I'll merge it.

2022-05-01 21:47 UTC, AcKindle3 commented
@synoet Teo, I've signed and pushed the commits. Please merge it into the main branch, so then I will check the working condition on iPadOS.

2022-05-03 01:52 UTC, synoet approved these changes

2022-05-03 01:53 UTC, merged